[dev]
command = "astro dev"


[build]
command = "pnpm build"
publish = "dist"
environment = { NODE_VERSION = "18" }

[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/script.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200
